# Generated by Django 4.2.7 on 2023-11-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_site', '0002_delete_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.IntegerField(help_text='Dosage of Med', max_length=100, verbose_name='dosage'),
        ),
    ]
