# Generated by Django 4.2.7 on 2023-11-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_site', '0003_alter_medicine_dosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.IntegerField(blank=True, help_text='Dosage of Med', null=True, verbose_name='dosage'),
        ),
    ]
